app/models.py
from app import db, login
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime
from hashlib import md5
import jwt
from flask import current_app
from time import time


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128), index=True, unique=True)
    about_me = db.Column(db.String(140))
    last_seen = db.Column(db.DateTime, default=datetime.utcnow)
    authy_id = db.Column(db.Integer, index=True, unique=True)

    def __repr__(self):
        return 'User: {}'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(
            digest, size)

    def get_reset_password_token(self, expires_in=600):
        return jwt.encode(
            {'reset_password': self.id, 'exp': time() + expires_in},
            current_app.config['SECRET_KEY'], algorithm='HS256')

    @staticmethod
    def verify_reset_password_token(token):
        try:
            id = jwt.decode(token, current_app.config['SECRET_KEY'],
                            algorithms=['HS256'])['reset_password']
        except:
            return
        return User.query.get(id)

    def two_factor_enabled(self):
        return self.authy_id is not None


@login.user_loader
def load_user(id):
    return User.query.get(int(id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, ValidationError, Length
from app.models import User


class EditProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    about_me = TextAreaField('About me', validators=[Length(min=0, max=140)])
    submit = SubmitField('Submit')

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError('Please use a different username.')

app/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from config import Config
from flask_moment import Moment
import logging
from logging.handlers import SMTPHandler, RotatingFileHandler
import os

db = SQLAlchemy()
migrate = Migrate()
mail = Mail()
login = LoginManager()
login.login_view = 'auth.login'
bootstrap = Bootstrap()
moment = Moment()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    mail.init_app(app)
    login.init_app(app)
    bootstrap.init_app(app)
    moment.init_app(app)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp, url_prefix='/errors')

    def start_ngrok():
        from pyngrok import ngrok

        url = ngrok.connect(5000)
        print('* Tunnel: ', url)

    if app.config.get('ENV') == 'development' and app.config['START_NGROK']:
        start_ngrok()

    if not app.debug and not app.testing:
        if app.config['MAIL_SERVER']:
            auth = None
            if app.config['MAIL_USERNAME'] or app.config['MAIL_PASSWORD']:
                auth = (app.config['MAIL_USERNAME'],
                        app.config['MAIL_PASSWORD']
                        )
            secure = None
            if app.config['MAIL_USE_TLS']:
                secure = ()
            mail_handler = SMTPHandler(
                mailhost=(app.config['MAIL_SERVER'], app.config['MAIL_PORT']),
                fromaddr='no-reply@' + app.config['MAIL_SERVER'],
                toaddrs=app.config['ADMINS'], subject='Push Notification Failure',
                credentials=auth, secure=secure)
            mail_handler.setLevel(logging.ERROR)
            app.logger.addHandler(mail_handler)
        if app.config['LOG_TO_STDOUT']:
            stream_handler = logging.StreamHandler()
            stream_handler.setLevel(logging.INFO)
            app.logger.addHandler(stream_handler)
        else:
            if not os.path.exists('logs'):
                os.mkdir('logs')
            file_handler = RotatingFileHandler('logs/twilio_authy.log',
                                               maxBytes=10240,
                                               backupCount=10
                                               )
            file_handler.setFormatter(logging.Formatter(
                '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'
            ))
            file_handler.setLevel(logging.INFO)
            app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('Twilio Authy 2FA')

    return app

from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app.main import bp
from flask import render_template, redirect, url_for, flash, request
from flask_login import current_user, login_required
from app.main.forms import EditProfileForm
from app.models import User
from datetime import datetime
from app import db


@bp.route('/')
@bp.route('/home')
@login_required
def home():
    return render_template('home.html',
                           title='Home'
                           )


@bp.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user.html', user=user, title='Profile')


@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()


@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('main.edit_profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('edit_profile.html',
                           title='Edit Profile',
                           form=form
                           )

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!-- Title Section -->
{% block title %}
    {% if title %}
        Twilio Authy | {{ title }}
    {% else %}
        Twilio Authy
    {% endif %}
{% endblock %}

<!-- Head Section -->
{% block head %}
    {{ super() }}
    <link rel="icon" type="image/png" href="{{url_for('static', filename = 'images/authy.svg')}}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
{% endblock %}

<!-- Link Styles -->
{% block styles %}
    {{ super() }}
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename = 'css/styles.css') }}">
{% endblock %}

<!-- Navbar Section -->
{% block navbar %}
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.home') }}">Twilio Authy</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">            
            <ul class="nav navbar-nav navbar-right">  
                {% if current_user.is_anonymous %}
                    <li><a href=" {{ url_for('auth.login') }} ">Login</a></li>
                {% else %}
                    <li><a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                {% endif %}                
            </ul>                       
        </div>
    </div>
</nav>
{% endblock %}

<!-- Blog Content Goes Here -->
{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-warning" role="alert"> {{ message }} </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {% block app_content %}
        
        {% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
{% endblock %}

app/templates/edit_profile.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 text-center">
            <h1>Edit Profile</h1>                                              
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">                
            <!-- Empty div -->
        </div>
        <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4 text-center">                                  
            <p>
                <a href="{{ url_for('main.user', username=current_user.username) }}">Back to profile page</a>
            </p>                                                     
        </div>
        <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">                
            <!-- Empty div -->
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">                
            <!-- Empty div -->
        </div>
        <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4 my-form">                                  
            {{ wtf.quick_form(form) }}                                                       
        </div>
        <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">                
            <!-- Empty div -->
        </div>
    </div>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}

{% block app_content %}
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 text-center">
        <!-- title -->
        <h1>Push Notifications with Twilio Authy</h1>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 text-center">
        <p>Hi {{current_user.username}}, do you want to enable push notifications?</p>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 text-center">
        <img class="img-fluid" style="max-width: 100%; height: auto;" src=" {{ url_for('static', filename = 'images/authy_notification.png') }}" alt="Push Notification"></p>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 text-center">
        <p>Go to your profile page</p>
    </div>
</div>
{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-4">
            <!-- Empty div -->
        </div>
        <div class="col-md-4">
            <table class="table">
                <tr width="70px">
                    <td><img src="{{ user.avatar(128) }}"></td>
                    <td>
                        <h1>User: {{ user.username }}</h1>

                        {% if user.about_me %}
                            <p>{{ user.about_me }}</p>
                        {% endif %}

                        {% if user.last_seen %}
                            <p>Last seen on: {{ moment(user.last_seen).format('LLL') }}</p>
                        {% endif %}

                        {% if user == current_user %}
                            <p><a href="{{ url_for('main.edit_profile') }}">Edit your profile</a></p>
                        {% endif %}
                        
                        <!-- Two factor authentication -->
                        {% if not user.two_factor_enabled() %}
                            <p>
                                <a href="{{ url_for('auth.enable_2fa') }}">Enable two-factor authenticaton using push notification</a>
                            </p>
                        {% else %}
                            <p>
                                <a href="{{ url_for('auth.disable_2fa') }}">Disable two-factor authenticaton using push notification</a>
                            </p>
                        {% endif %}
                    </td>
                </tr>
            </table>
        </div>
        <div class="col-md-4">
            <!-- Empty div -->
        </div>
    </div>
{% endblock %}